import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import { RecordsSearchBar } from "../components/searchBars/RecordSearchBar";

export default function Home() {
  const endpoints = [{ Login: "/login" }, { Expenses: "/finances/expenses" }];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <main className={styles.main}>
        <ul>
          {endpoints.map((endpoint, idx) => {
            const [key, value] = Object.entries(endpoint).flat();
            console.log(key, value);
            return (
              <li key={idx}>
                <Link href={`${value}`} passHref>
                  <a>{key}</a>
                </Link>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}
